apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs-test
  description: testing the techdocs plugin
  annotations:
    github.com/project-slug: frontdesk-development/techdocs-test
    backstage.io/techdocs-ref: github:https://github.com/frontdesk-development/techdocs-test
spec:
  type: documentation
  lifecycle: experimental
  owner: perry.manuk@trivago.com
